-- ============================================================================
-- 1. CREATE TABLES (Membuat Struktur Database)
-- ============================================================================

-- Tabel Produk (products)
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    excerpt TEXT,
    content TEXT,
    cover_image TEXT,
    link TEXT,
    price TEXT,
    is_featured BOOLEAN DEFAULT false,
    tags TEXT, -- Disimpan sebagai stringified JSON array
    published_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabel Proyek/Galeri (projects)
CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    summary TEXT,
    description TEXT,
    content TEXT,
    cover_image TEXT,
    cover_alt TEXT,
    tech TEXT,   -- Disimpan sebagai stringified JSON array
    role TEXT,
    year TEXT,
    featured BOOLEAN DEFAULT false,
    client TEXT,
    duration TEXT,
    links TEXT,  -- Disimpan sebagai stringified JSON object
    images TEXT, -- Disimpan sebagai stringified JSON array
    published_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabel Artikel Blog (blog_posts)
CREATE TABLE IF NOT EXISTS blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    excerpt TEXT,
    content TEXT,
    cover_image TEXT,
    read_time INTEGER DEFAULT 0,
    is_featured BOOLEAN DEFAULT false,
    tags TEXT, -- Disimpan sebagai stringified JSON array
    published_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- (Opsi: Hapus tanda "--" di baris bawah ini jika ingin membersihkan tabel sebelum insert data baru)
-- TRUNCATE TABLE products, projects, blog_posts RESTART IDENTITY;


-- ============================================================================
-- 2. INSERT DATA (Mengisi Data Contoh ke Database)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Insert Data: Produk
-- ----------------------------------------------------------------------------
INSERT INTO products (title, slug, excerpt, content, cover_image, link, price, is_featured, tags) VALUES
('Paket Seminar Basic', 'paket-seminar-basic', 'Paket hemat untuk seminar skala kecil hingga menengah.', 'Paket ini mencakup Tas Spunbond, Blocknote A5, Pulpen Standar, dan ID Card. Sangat cocok untuk acara kampus atau workshop singkat.', '/uploads/1783357913446-fjl512-paket_seminar_basic.webp', '/contact', 'Rp 25.000 / pax', true, '["basic", "hemat", "tas spunbond", "seminar"]'),
('Paket Seminar Profesional', 'paket-seminar-profesional', 'Pilihan terpopuler dengan tas kanvas dan notes eksklusif.', 'Dilengkapi dengan Tas Kanvas tebal, Blocknote Hardcover, Pulpen Metal, Tumbler Plastik, dan Lanyard. Ideal untuk konferensi tingkat nasional.', '/uploads/1783179353872-ux2qs7-paket_seminar_pro.webp', '/contact', 'Rp 75.000 / pax', true, '["profesional", "kanvas", "tumbler", "konferensi"]'),
('Paket Seminar Premium Eksklusif', 'paket-seminar-premium', 'Paket mewah dengan ransel laptop dan merchandise premium.', 'Cocok untuk tamu VIP. Berisi Ransel Laptop, Buku Agenda Kulit Premium, Flashdisk Custom 16GB, Tumbler Suhu Stainless, dan Kaos Polo.', '/uploads/1783687348582-mqp456-welcome-kit.webp', '/contact', 'Rp 250.000 / pax', true, '["premium", "vip", "ransel", "flashdisk"]'),
('Souvenir Tumbler Custom', 'souvenir-tumbler-custom', 'Tumbler stainless steel dengan grafir logo perusahaan.', 'Tumbler tahan panas/dingin hingga 12 jam. Dapat digrafir dengan logo atau nama peserta menggunakan teknologi laser presisi.', '/uploads/1783311687628-hs291e-bottle.webp', '/contact', 'Rp 45.000 / pcs', false, '["tumbler", "souvenir", "custom logo"]'),
('Custom Tote Bag Blacu', 'custom-tote-bag-blacu', 'Tote bag ramah lingkungan dengan sablon desain acara.', 'Tote bag berbahan kain blacu yang kuat dan ramah lingkungan. Cetak sablon 1-2 warna sesuai desain tema seminar Anda.', '/uploads/1783247973940-5sgzje-pouch2.png', '/contact', 'Rp 15.000 / pcs', false, '["tote bag", "blacu", "eco-friendly"]');

-- ----------------------------------------------------------------------------
-- Insert Data: Proyek/Galeri
-- ----------------------------------------------------------------------------
INSERT INTO projects (title, slug, summary, description, content, cover_image, cover_alt, tech, role, year, featured, client, duration, links, images) VALUES
('Seminar Nasional Pendidikan 2026', 'seminar-nasional-pendidikan-2026', 'Penyediaan 500 paket seminar kit standar untuk peserta dari seluruh Indonesia.', 'Kami bangga menjadi mitra pengadaan seminar kit untuk Seminar Nasional Pendidikan 2026 yang dihadiri oleh guru dan praktisi pendidikan dari seluruh Nusantara.', 'Acara ini membutuhkan pengiriman yang cepat dan presisi. Kami menyediakan 500 tote bag sablon, blocknote, pulpen, dan sertifikat cetak yang diselesaikan dalam waktu 1 minggu.', '/uploads/1783517552510-lh7t5e-portofolio.png', 'Suasana Seminar Nasional', '["Tote Bag", "Blocknote", "Sertifikat"]', 'Vendor Merchandise', '2026', true, 'Universitas Indonesia', '1 Minggu', '{}', '[]'),
('Konferensi Teknologi & Inovasi (TechCon)', 'techcon-2026', 'Distribusi 1000 paket premium VIP untuk startup founder dan investor.', 'TechCon membutuhkan perlengkapan yang merepresentasikan inovasi dan kemewahan. Kami mensuplai ransel laptop dan tumbler pintar.', 'Peserta sangat menyukai tumbler pintar dengan pengukur suhu yang kami berikan. Logo TechCon digrafir elegan pada setiap tumbler.', '/uploads/1783351769512-smf6gf-seminar1.png', 'TechCon 2026 VIP Kit', '["Ransel Laptop", "Smart Tumbler", "Flashdisk Custom"]', 'Vendor Utama', '2026', true, 'TechCorp Indonesia', '3 Minggu', '{}', '[]'),
('Workshop Digital Marketing', 'workshop-digital-marketing', 'Pengadaan 200 paket alat tulis dan ID card eksklusif.', 'Untuk workshop intensif selama 2 hari, peserta membutuhkan alat tulis yang nyaman dan ID Card yang kokoh.', 'Kami mendesain khusus Lanyard dengan warna brand klien dan blocknote ring yang mudah digunakan selama sesi praktek digital marketing.', '/uploads/1783517693698-b7aiqk-mockup_souvenir_premium_kantor.webp', 'Alat tulis workshop', '["Lanyard Custom", "Blocknote Ring", "Pulpen Stylus"]', 'Vendor Sablon & Cetak', '2025', false, 'Marketer ID', '5 Hari', '{}', '[]'),
('Rapat Kerja Nasional Kementerian X', 'rakernas-kementerian', 'Paket seminar formal (tas dokumen dan agenda kulit) untuk 300 pejabat.', 'Rakernas membutuhkan tampilan yang sangat formal dan rapi. Kami menyediakan map dokumen kulit sintetis dan pulpen besi.', 'Kualitas jahitan map dokumen menjadi fokus utama kami untuk memastikan kesan elegan dan tahan lama bagi para peserta.', '/uploads/1783686048996-zhdpwr-komposisi-meja-kerja-minimalis-elegan.webp', 'Meja kerja rapi', '["Agenda Kulit", "Map Dokumen", "Pulpen Besi"]', 'Vendor Pengadaan', '2025', false, 'Kementerian X', '2 Minggu', '{}', '[]'),
('Pelatihan Kepemimpinan Mahasiswa BEM', 'pelatihan-bem', 'Paket outbound dan seminar (kaos dan pouch) untuk 150 mahasiswa.', 'Selain sesi ruangan, acara ini memiliki sesi outbound. Kami menyediakan pouch tahan air dan kaos kegiatan yang menyerap keringat.', 'Pouch custom yang kami buat ternyata sangat berguna bagi mahasiswa untuk menyimpan smartphone mereka selama sesi lapangan.', '/uploads/1783268346469-e1ye8v-outbound-katun-coban-talun-batu.png', 'Pouch kegiatan lapangan', '["Kaos Kegiatan", "Pouch Anti Air", "Topi Sablon"]', 'Konveksi & Merchandise', '2025', false, 'BEM Universitas Y', '2 Minggu', '{}', '[]');

-- ----------------------------------------------------------------------------
-- Insert Data: Artikel Blog
-- ----------------------------------------------------------------------------
INSERT INTO blog_posts (title, slug, excerpt, content, cover_image, read_time, is_featured, tags) VALUES
('Panduan Lengkap Memilih Paket SeminarKit', 'panduan-memilih-seminarkit', 'Jangan salah pilih! Ketahui cara menyesuaikan paket dengan budget.', 'Memilih perlengkapan seminar seringkali membingungkan. Pertama, pastikan siapa target audiens Anda. Jika mahasiswa, paket basic sudah cukup...', '/uploads/1783178103412-gd80xb-artikelblog.webp', 5, true, '["Panduan", "Tips", "Budgeting"]'),
('Mengapa Souvenir Ramah Lingkungan Diminati?', 'souvenir-ramah-lingkungan', 'Tren eco-friendly kini merambah ke dunia merchandise acara.', 'Menggunakan tote bag dari bahan daur ulang tidak hanya menyelamatkan bumi, tetapi juga meningkatkan citra positif perusahaan Anda...', '/uploads/1783517812554-xw6aas-artikel-atas.webp', 4, true, '["Eco-Friendly", "Tren", "Green Event"]'),
('Tips Menghemat Budget Merchandise', 'tips-menghemat-budget-merchandise', 'Anda punya budget terbatas? Ini rahasia agar kit Anda tetap elegan.', 'Fokuslah pada desain, bukan sekadar harga barang. Sebuah tote bag blacu murah akan terlihat sangat premium jika desain sablonnya minimalis...', '/uploads/1783322932782-6j9hsz-artikelblog__1_.webp', 3, false, '["Budget", "Desain", "Tips"]'),
('Pentingnya Name Tag Profesional dalam Acara', 'pentingnya-name-tag-profesional', 'Name tag bukan sekadar tanda pengenal, tapi juga alat networking.', 'ID card yang desainnya jelas dan tulisannya besar akan sangat memudahkan peserta untuk saling bertegur sapa dan melakukan networking...', '/uploads/1783351569517-u87c5a-strategi-atas.webp', 4, false, '["Networking", "Lanyard", "Event Management"]'),
('Tren Souvenir Seminar & Konferensi 2026', 'tren-souvenir-seminar-2026', 'Tinggalkan blocknote biasa! Ini inovasi merchandise tahun ini.', 'Smart tumbler yang menampilkan suhu air dan UV sterilizer box mini kini mulai menggantikan jam dinding sebagai souvenir favorit korporat...', '/uploads/1783348689750-uqxre6-9.webp', 6, false, '["Tren 2026", "Teknologi", "Inovasi"]');
